# Generated by Django 6.1.2 on 2026-10-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_donation_campaign_donation_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
