# Generated by Django 6.1.2 on 2026-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='motivation',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='quote',
            field=models.TextField(blank=True, help_text='Quote or motivation on why you want to volunteer', null=True),
        ),
    ]
