# Generated by Django 6.1.2 on 2026-10-09 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_volunteer_options_remove_volunteer_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='key_objectives',
            field=models.TextField(blank=True, help_text='Enter key objectives (one per line).', null=True),
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='campaigns/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.campaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
