# Generated by Django 6.1.2 on 2026-10-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_facebook_link_campaign_instagram_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Main Admin', 'Main Admin (Superuser)'), ('Head of Programs', 'Head of Programs (Campaign Management)'), ('HR Manager', 'HR Manager (Volunteers & Team Members)'), ('Communications', 'Communications (Contact Messages)')], default='Head of Programs', help_text='Role determines dashboard administrative access and capabilities.', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
